# Travis-CI Build for Jedi.Caching
# see travis-ci.org for details

language: csharp
dist: trusty
mono: none
dotnet: 3.1.101
script:
  - dotnet restore
  - dotnet build
notifications:
  slack: jedicontributors:1iwMEyHygp3cJUsXL6AljEka