# Travis-CI Build for Jedi.Caching
# see travis-ci.org for details

sudo: required
dist: bionic
language: csharp
solution: Jedi.Caching.sln
mono: none
dotnet: 3.1.101
script:
  - dotnet restore
  - dotnet build
notifications:
  slack: jedicontributors:1iwMEyHygp3cJUsXL6AljEka

  